free4talk/urls.py
from django.contrib import admin
from django.urls import path, include   


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("scraper.urls"))
]

scraper/urls.py
from django.urls import path

from . import views

app_name = "scraper"  

urlpatterns = [
    path("", views.index, name="index"),
    path('update-db', views.update_db, name='update_db'),
    path("search", views.search, name="search")

]

scraper/models.py
from email.policy import default
from django.db import models
import requests
from django.utils import timezone
# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=200)
    user_id = models.CharField(max_length=200)
    followers = models.PositiveSmallIntegerField()
    following = models.PositiveSmallIntegerField()
    friends = models.PositiveSmallIntegerField()
    avatar_url = models.URLField()
    time = models.DateTimeField(default=timezone.now)



# the following part of the code it to update the data base by scraping the website "free4talk"
class JsonRequest():
    # this url will return json data including all info for online user 
    # like thier names and id and so on 
    __url = "https://free4talk-sync.herokuapp.com/sync/get/free4talk/groups/?a=sync-get-free4talk-groups"
    
    status = None
    
    # make a request and return the data as json data that python can handel
    @classmethod
    def get_json_data(cls):
        res =requests.post(cls.__url)
        res.encoding='utf-8-sig'
        cls.status = res.status_code
        return res.json()
    
    # just for returning the request status code 
    @classmethod
    def __str__(cls):
        return cls.status       

# this class will get the data recvived from the JsonRequest class as a param and then parse it 
# and also can save the data into the data base in scraper_user tabel
class ParsedData():
    
    def __init__(self, data):
        self.__data = data
        self.num_users = 0
    
    def save_data(self):
        # catch any exception occures during the processes and return false if anything goes wrong
        # so then views can return the right page or 500 page 
        try:
            for room in self.__data["data"]:
                for user in self.__data["data"][room]["clients"]:
                    # if user found then update his thier data
                    try:
                        x = User.objects.get(user_id=user["id"])
                        x.name = user["name"]
                        x.followers = user["followers"]
                        x.following = user["following"]
                        x.friends = user["friends"]
                        x.avatar = user["avatar"]
                        x.time=timezone.now()
                        x.save()
                    # if user not found then add it to the database                        
                    except User.DoesNotExist:                        
                        user_x = User(
                            name=user["name"], user_id=user["id"], followers=user["followers"], following=user["following"],
                            friends=user["friends"], avatar_url=user["avatar"], time=timezone.now()
                        )
                        user_x.save()
                        self.num_users += 1
                                           
            return True
        except (ValueError, KeyError): 
            return False 

    def __str__(self):     
        return F"{self.num_users}"

scraper/forms.py
from django import forms

class UserId(forms.Form):
    user_id = forms.CharField(max_length=200)

class UserName(forms.Form):
    name = forms.CharField(max_length=200)    

scraper/views.py
from wsgiref.validate import validator
from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import Q

from . import models 
from .forms import UserId, UserName


# Create your views here.
def update_db(request):
    data = models.JsonRequest.get_json_data()
    ob = models.ParsedData(data)
    if ob.save_data():
        users_num = models.User.objects.count()
        return render(request, "scraper/update_db.html", {"new_users": ob.num_users, "users_updated":users_num})
    return HttpResponse("503")        


def index(request):
    users_num = models.User.objects.count()
    return render(request, "scraper/index.html", {"users_num": users_num})


def search(request):
    if request.method == "POST":
        user_id, user_name = UserId(request.POST), UserName(request.POST)
    
        if user_id.is_valid() and user_name.is_valid():
            user_id, user_name = user_id.cleaned_data, user_name.cleaned_data
            user_id, user_name = user_id["user_id"], user_name["name"]

            try:
                user = models.User.objects.get(Q(name=user_name) & Q(user_id=user_id)) 
                return render(request, "scraper/res.html", {"user_data": user})
            
            except(models.User.DoesNotExist, TypeError):
                
                try:
                    users = models.User.objects.filter(Q(name=user_name) | Q(user_id=user_id)) 
                    return render(request, "scraper/res.html", {"users": users})
                
                except(models.User.DoesNotExist, TypeError):                    
                    return HttpResponse("404 User Not Found")
                            
        else:
            return render(request, "scraper/search.html", {"user_id":UserId, "user_name": UserName})

    return render(request, "scraper/search.html", {"user_id":UserId, "user_name": UserName})        



def delete(request):
    ...
    #TODO

def reg(request):
    if request.method == "POST":
        ...
        
    return render(request, "reg.html")    

scraper/templates/scraper/index.html
{% extends "scraper/layout.html" %}

{% block title %}
    Index Page
{% endblock %}
    
{% block nav %}
<div class="container"> 
     <h5> <a href="{% url 'scraper:update_db' %}"> click here to update the database it might take time </a></h5>
     <h5><a href="{% url 'scraper:search' %}">click here to Search</a></h5>
</div>
{% endblock %}

{% block body %}
<div class="container"> 
    <h1>Index Page !</h1>

    <h3>
    for now we have {{users_num}} users in our database
</div>
</h3>
{% endblock %}

scraper/templates/scraper/layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>

    <div class="main col-lg-10 col-md-9">
        {% block body %}
        {% endblock %}
    </div>        

    <div class="container">
    {% block nav %}
    {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

scraper/templates/scraper/reg.html
{}

scraper/templates/scraper/res.html
{% extends "scraper/layout.html" %}

{% block body%}
<div class="container">

    {% if users %}
        <h2> similer data found in the database </h2>
        <br>
        <br>
        {% for user in users %}
            <h4> Naem: {{user.name}} <h4>
                <img src="{{user.avatar_url}}">
            <h4>ID : {{user.user_id}}, Followers: {{user.followers}}, Follwing: {{user.following}}, Friends: {{user.friends}}, Last Time Seen: {{user.time}} </h4>
            <br>
            {% endfor %}
    {% endif %}
    <h5><a href="{% url 'scraper:search' %}">click here to Search</a></h5>
    <h5> <a href="{% url 'scraper:index' %}"> Index Page </a></h5>
    <h5> <a href="{% url 'scraper:update_db' %}"> click here to update the database it might takea few seconds </a></h5>
        

    {% if user_data %}
        <h2> Naem: {{user_data.name}} <h2>
            <img src="{{user_data.avatar_url}}">
        </h2> ID : {{user_data.user_id}}, Followers: {{user_data.followers}}, Follwing: {{user_data.following}}, Friends: {{user_data.friends}}, Last Time Seen: {{user_data.time}} </h2>
    {% endif %}
</div>
{% endblock %}

scraper/templates/scraper/search.html
{% extends "scraper/layout.html" %}


{% block body %}
<br>
<br>
<div class="container">
    <h5> <a href="{% url 'scraper:index' %}"> Index Page </a></h5>
    <h5> <a href="{% url 'scraper:update_db' %}"> click here to update the database it might take a few seconds </a></h5>

<h2>you can search by only the user name or just user id </h2>
<br>
<h4>if possibale you can search with both name and id to get accurate results. </h4>

<br>
<h4> if you have only the name or only the user_id enter it and fill the other field with 0 or any arg</h4>
     
<br>

<form action="{% url 'scraper:search' %}" method="post">
    <div class="mb-3">

    {% csrf_token %}
    {{user_id}}
    {{user_name}}
    <button type="submit" class="btn btn-primary">Search</button>
        </div>
</form>    
{% endblock %}

</div>

scraper/templates/scraper/update_db.html
{% extends "scraper/layout.html" %}

{% block title%}
    update db
{% endblock%}
    
{% block nav %}
    <h5><a href="{% url 'scraper:index' %}">Index Page</a></h5>
    <h5><a href="{% url 'scraper:search' %}">click here to Search</a></h5>
{% endblock %}

{% block body %}
<h3>
    <br>
    <br>
    <div class="continer">
    <p>added {{new_users}} new users  </p>
    <p>updated {{users_updated}} users data </p>
    </div>
</h3>
<div>
    
</div>
{% endblock %}